version: "3.9"

services:
  backend:
    build:
      context: backend/app-python/
    environment:
      - REGION_NAME=ru-central1
    env_file:
      - .env
    restart: always
    ports:
      - 8181:8000
  ml-server:
    build:
      context: ml-commits/backend/app-python/
    restart: always
    ports:
      - 9002:8000
  git-server:
    build:
      context: backend/app-git/
    restart: always
    volumes:
      - /home/ilinivan/repos:/app/repos
    ports:
      - 9001:8000
  ml-resume:
    build:
      context: ml/backend/app-python/
    environment:
      - REGION_NAME=ru-central1
    env_file:
      - .env
    restart: always
    ports:
      - 5000:8000
  frontend:
    build:
        context: ./frontend
        dockerfile: Dockerfile
    restart: always
    ports:
        - "3000:3000"
  postgres:
    image: postgres:16

    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - "./backend/app-python/.env"
    ports:
      - "9500:5432"


volumes:
  postgres-data: